@K4U2_HostAddress = ç

GET {{K4U2_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{K4U2_HostAddress}}/api/ContentApi
Content-Type: application/json

{
  "message": "hur gammal kan ett bi bli?",
  "category": "djur"
}

### 
GET {{K4U2_HostAddress}}/api/ContentApi
Accept: application/json

### 
DELETE {{K4U2_HostAddress}}/api/ContentApi
